### ISSUE TITLE
[Request] SlimRecents apk

### ISSUE THREAD

**Issue by pirasalbe** [ezio84/abc_packages_apps_SlimRecents#2]
Hi, is it possible to build a SlimRecents apk to install in every rom?
I thinks that it is the best multitasker for android so far.

**Comment by ezio84** [comment]
Not possible atm, i don't plan to do it.

**Comment by kusti420** [comment]
looking forward to it

**Comment by Barkuti** [comment]
Looking forward to it too. If there's anything we can do to encourage this, please say so.
Best regards,
Salvador
